import tkinter
root = tkinter.Tk()
root.geometry("400x400")
root.title("My To Do Lists")
label = tkinter.Label(root, text="To Do Lists", font=('10'))
label.pack(padx= 5, pady=5)
textbox = tkinter.Text(root,height=3, font=('Times New Roman', 8))
password = tkinter.Entry()
textbox.pack(padx= 5,pady=5)
password.pack()
button = tkinter.Button(root,  text="click here boii", )
button.pack(padx=3, pady= 3 )
checkbutton = tkinter.Checkbutton(root, text="click here")
checkbutton.pack()
buttonframe = tkinter.Frame(root)
buttonframe.columnconfigure(0, weight= 1)
buttonframe.columnconfigure(1, weight= 1)
buttonframe.columnconfigure(2, weight= 1)
button1 = tkinter.Button(buttonframe, text="1", font= (10))
button1.grid(row=0, column=0, sticky=tkinter.W+tkinter.E) 
button2 = tkinter.Button(buttonframe, text="2", font= (10))
button2.grid(row=0, column=1, sticky=tkinter.W+tkinter.E) 
button3 = tkinter.Button(buttonframe, text="3", font= (10))
button3.grid(row=0, column=2, sticky=tkinter.W+tkinter.E) 
button4 = tkinter.Button(buttonframe, text="4", font= (10))
button4.grid(row=1, column=0, sticky=tkinter.W+tkinter.E) 
button5 = tkinter.Button(buttonframe, text="5", font= (10))
button5.grid(row=1, column=1, sticky=tkinter.W+tkinter.E) 
button6 = tkinter.Button(buttonframe, text="6", font= (10))
button6.grid(row=1, column=2, sticky=tkinter.W+tkinter.E) 
buttonframe.pack(fill='x')
newbutton = tkinter.Button(root, text="another one ")
newbutton.place(x="280", y ="280", height=100, width=100)
root.mainloop()